# Generated by Django 3.2.8 on 2025-11-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Acuicolas', 'Acuícolas'), ('Pesqueros', 'Pesqueros'), ('Ganaderos', 'Ganaderos'), ('Vegetales', 'Vegetales')], max_length=100),
        ),
    ]
